### ISSUE TITLE
help for start!

### ISSUE THREAD

**Issue by SiNaPsEr0x** [LuisMayo/TelegramPictureExchange#9]
Hi, I insert setting conf and compiled...

$ npm fund
telegram-picture-exchange@1.2.0
└─┬ glob@7.1.6
  └── url: https://github.com/sponsors/isaacs

well... for start bot?

**Comment by LuisMayo** [comment]
@SiNaPsEr0x Hi
In order to start your bot you should run node build/index.js

I will add it to package.json later

Thank you very much for your enquiry

**Comment by SiNaPsEr0x** [comment]
where is the folder? 
$ npm install
audited 170 packages in 1.425s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

after npm install build folder is missing

**Comment by SiNaPsEr0x** [comment]
sorry bot runned.... 
but 

 "adminChat": "YOUR ADMIN CHANNEL HERE",


in conf adminchat who is? nickname or group?

**Comment by LuisMayo** [comment]
@SiNaPsEr0x Hi

You should use tsc command. After using it the build folder will appear

Thanks!

**Comment by SiNaPsEr0x** [comment]
(node:23687) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 17)
New photo! at Fri Feb 28 2020 16:23:25 GMT+0100 (Central European Standard Time)
 


for fix this error? and adminchat insert ID of chat insert to readme pls

**Comment by SiNaPsEr0x** [comment]
whats is the command to bot?

**Comment by LuisMayo** [comment]
> (node:23687) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 17)
> New photo! at Fri Feb 28 2020 16:23:25 GMT+0100 (Central European Standard Time)
> 
> for fix this error? and adminchat who is?

Adminchat is the ID of the chat you wish to use to administrate the bot. When users report pictures these pictures will be sent to the admin chat

That error is usually raised when the bot is trying to message someone who hasn't started conversation with. It could be happening of you didn't set the admin chat properly



> whats is the command to bot?

To use the bot one user must send it a photo, then another user must do the same
The bot actually uses chat IDs so you can put your bot in a group and test it by sending photos from private chat and then sending photos from the group (in order for this to work you should reply to a bot message when using it on a group)

Thanks!
